name: "clj-kondo lint"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'config.edn'
  push:
    paths:
      - 'config.edn'
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2023.03.17'

      - uses: actions/checkout@v3

      - name: clj-kondo lint
        run: clj-kondo --lint config.edn --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
