---
name: Lint Clojure LSP
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'config.edn'
      - 'cljfmt.edn'
  push:
    paths:
      - 'config.edn'
      - 'cljfmt.edn'
    branches:
      - main

jobs:
  lint-lsp-config:
    name: Lint LSP Config
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Job automatically triggered by ${{ github.event_name }}"
      - run: echo "🐧 Job running on ${{ runner.os }} server"
      - run: echo "🐙 Using ${{ github.ref }} branch from ${{ github.repository }} repository"

      - name: "Checkout code"
        uses: actions/checkout@v3.0.2
      - run: echo "🐙 ${{ github.repository }} repository was cloned to the runner."

      - name: clj-kondo
        uses: nnichols/clojure-lint-action@v2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          pattern: '*.edn'

      - run: echo "🎨 style and format of Clojure code checked"

      - run: echo "🍏 Job status is ${{ job.status }}."
